### PR TITLE
Version 0.3.0 release

### PR DESCRIPTION
**Pull request by nikhil**
- Save refresh token (#45)
- Added request.txt, and page options for runs (#47)
- Added option to specify apps for runs (#49)
- Adding filetypes argument (#51)

### CODE REVIEW

**Review by buehlere — CHANGES_REQUESTED** [review]
Hi @nikhil, this looks great! 

Two small things: 
- Would it be possible to add [--apps="apps"] to the docs for the new run feature to indicate that it's best to wrap app names in quotes since they sometimes have spaces? 

- could we add this branch to the release: https://github.com/mskcc/beagle_cli/tree/feature/extend-files?  It just adds the file type argument to the files endpoint. 

I'm also happy to make these changes / feel free to ignore!

**Comment by nikhil** [comment]
Great suggestions! I have added those fixes in.

**Review by buehlere — COMMENTED** [review]
awesome, thank you!

**Review by buehlere — APPROVED** [review]
awesome, thank you!

**Pull request merged**
